### ISSUE TITLE
panic if send SIGINT

### ISSUE THREAD

**Issue by shogo82148** [shogo82148/server-starter#7]
on https://github.com/shogo82148/server-starter/commit/edf8769b3cfcd10b43e50e4efbabd9b8b5951aae

```
^C2019/01/05 23:00:01 received interrupt, sending TERM to all workers:2871
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x10f482b]

goroutine 1440 [running]:
os.(*ProcessState).sys(...)
        /usr/local/Cellar/go/1.11.4/libexec/src/os/exec_posix.go:78
os.(*ProcessState).Sys(...)
        /usr/local/Cellar/go/1.11.4/libexec/src/os/exec.go:159
github.com/shogo82148/server-starter.(*worker).watch(0xc00009cd80)
        /Users/shogoichinose/src/github.com/shogo82148/server-starter/starter.go:291 +0x2db
created by github.com/shogo82148/server-starter.(*worker).Watch
        /Users/shogoichinose/src/github.com/shogo82148/server-starter/starter.go:273 +0x63
```

**Comment by shogo82148** [comment]
fixed by #12
